In [3]:
import numpy as np


In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [7]:
#%time for _ in range(10): my_arr2 = my_arr * 2 CPU times: user 20 ms, sys: 50 ms, total: 70 ms
#Wall time: 72.4 ms

# The NumPy ndarray: A Multidimensional Array Object

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python

In [8]:
data = np.random.randn(2, 3)

In [9]:
data

array([[ 1.29749794,  1.12614976,  0.94196396],
       [ 0.08713885, -0.39601642,  1.16561771]])

In [10]:
data * 10

array([[12.97497944, 11.2614976 ,  9.41963965],
       [ 0.87138853, -3.96016417, 11.65617709]])

In [11]:
data +data

array([[ 2.59499589,  2.25229952,  1.88392793],
       [ 0.17427771, -0.79203283,  2.33123542]])

In [12]:
data.shape # tell how many row and coluns

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [14]:
data1 = [6, 7.5, 8, 0, 1]
    

In [15]:
arr1 = np.array(data1)


In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [20]:
arr2 = np.array(data2)


In [21]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.empty((2,3,2))   # uninititlaised garbage value /zeros

array([[[-1.49166815e-154, -1.49166815e-154],
        [ 5.43472210e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[-1.49166815e-154, -2.32035218e+077],
        [ 3.95252517e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]]])

In [28]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr = np.array([1, 2, 3, 4, 5])

In [30]:
arr.dtype

dtype('int64')

In [31]:
float_arr = arr.astype(np.float64)

In [32]:
 float_arr.dtype

dtype('float64')

In [33]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [34]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [35]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [36]:
 numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [37]:
int_array = np.arange(10)

In [38]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [39]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:

empty_uint32 = np.empty(8, dtype='u4')

In [42]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [7]:
arr= np.array([[1., 2., 3.], [4., 5., 6.]])

In [44]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
arr * arr 

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [46]:
arr -arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [49]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [50]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [51]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [8]:
arr = np.arange(10)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]

5

In [11]:
arr[5:8]=80
arr

array([ 0,  1,  2,  3,  4, 80, 80, 80,  8,  9])

In [12]:
arr_slice =arr[5:8]  # 5 to 7 index elements assigning to arr_slice 

In [13]:
arr_slice

array([80, 80, 80])

In [14]:
arr_slice[1]=12345

In [15]:
arr  # from arr_slice[1] changed to 12345

array([    0,     1,     2,     3,     4,    80, 12345,    80,     8,
           9])

array([    0,     1,     2,     3,     4,    80, 12345,    80,     8,
           9])

In [19]:
arr_slice[:]=68  # assignig all element 

In [20]:
arr

array([ 0,  1,  2,  3,  4, 68, 68, 68,  8,  9])

In [21]:
arr2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
arr2d[2]

array([7, 8, 9])

In [23]:
arr2d[0][2]

3

In [24]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [25]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
 old_values = arr3d[0].copy()

In [28]:
 arr3d[0] = 42

In [29]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
 arr3d[0] = old_values   # back to old values arr3d[1, 0]

In [31]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr3d[1, 0]

array([7, 8, 9])

In [33]:
x = arr3d[1]

In [34]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [36]:
x[0]

array([7, 8, 9])

In [37]:
arr

array([ 0,  1,  2,  3,  4, 68, 68, 68,  8,  9])

In [38]:
arr[1:6]

array([ 1,  2,  3,  4, 68])

In [39]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr2d[:2, 1:]  # :2  -> print 0,1 row, 1: -> start values from 1st column 

array([[2, 3],
       [5, 6]])

In [42]:
arr2d[1, :2] # second  row values 0,1 columns :2

array([4, 5])

In [43]:
arr2d[:2, 2]  # first 2 row and 3 rd column values  Im not very clear about  
# ([3],
#    [6])

array([3, 6])

In [44]:
arr2d[:, :1]  # all rows, 1st column

array([[1],
       [4],
       [7]])

In [45]:
arr2d[:2, 1:] = 0  # first 2 row, second thrid column assigned with 0

# Boolean Indexing

In [46]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [61]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [62]:
data = np.random.randn(7, 4)

In [63]:
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [64]:
data

array([[-0.70513577,  0.77250426,  0.47620569,  0.6969188 ],
       [-0.80986843,  1.08057487,  0.37162582,  0.46907431],
       [-1.03744684,  0.12714924,  0.12082973,  1.56799087],
       [-0.72282352,  0.02970937, -1.22790166, -0.62232743],
       [ 2.84604722,  0.21634366,  0.76887295,  0.61418852],
       [ 1.47103172,  0.15961656,  0.7209183 , -0.69845512],
       [-1.21443852, -0.71110227, -1.11751159, -1.02584242]])

In [65]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [66]:
data[names == 'Bob']

array([[-0.70513577,  0.77250426,  0.47620569,  0.6969188 ],
       [-0.72282352,  0.02970937, -1.22790166, -0.62232743]])

In [67]:
data[names == 'Bob', 2:]  #column 3rd and 4th

array([[ 0.47620569,  0.6969188 ],
       [-1.22790166, -0.62232743]])

In [68]:
data[names == 'Bob', 3]  # column 3 

array([ 0.6969188 , -0.62232743])

In [69]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [70]:
 data[~(names == 'Bob')]   # not with bob index

array([[-0.80986843,  1.08057487,  0.37162582,  0.46907431],
       [-1.03744684,  0.12714924,  0.12082973,  1.56799087],
       [ 2.84604722,  0.21634366,  0.76887295,  0.61418852],
       [ 1.47103172,  0.15961656,  0.7209183 , -0.69845512],
       [-1.21443852, -0.71110227, -1.11751159, -1.02584242]])

In [71]:
cond = names == 'Bob'

In [72]:
data[~cond]     # not with bob columns

array([[-0.80986843,  1.08057487,  0.37162582,  0.46907431],
       [-1.03744684,  0.12714924,  0.12082973,  1.56799087],
       [ 2.84604722,  0.21634366,  0.76887295,  0.61418852],
       [ 1.47103172,  0.15961656,  0.7209183 , -0.69845512],
       [-1.21443852, -0.71110227, -1.11751159, -1.02584242]])

In [73]:
mask = (names == 'Bob') | (names == 'Will') # both Bob Will

In [74]:
mask

array([ True, False,  True,  True,  True, False, False])

In [75]:
data[mask]

array([[-0.70513577,  0.77250426,  0.47620569,  0.6969188 ],
       [-1.03744684,  0.12714924,  0.12082973,  1.56799087],
       [-0.72282352,  0.02970937, -1.22790166, -0.62232743],
       [ 2.84604722,  0.21634366,  0.76887295,  0.61418852]])

In [76]:
data[data < 0] = 0

In [77]:
data

array([[0.        , 0.77250426, 0.47620569, 0.6969188 ],
       [0.        , 1.08057487, 0.37162582, 0.46907431],
       [0.        , 0.12714924, 0.12082973, 1.56799087],
       [0.        , 0.02970937, 0.        , 0.        ],
       [2.84604722, 0.21634366, 0.76887295, 0.61418852],
       [1.47103172, 0.15961656, 0.7209183 , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [78]:
data[names != 'Joe'] = 7 # index !=Joe assign 7 
 

In [79]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.08057487, 0.37162582, 0.46907431],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.47103172, 0.15961656, 0.7209183 , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

# Fancy Indexing
Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays. Suppose we had an 8 × 4 array:

In [80]:
arr = np.empty((8, 4))

In [82]:
for i in range(8):
    arr[i]=i
arr    

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [83]:
 arr[[4, 3, 0, 6]] # rows

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [84]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [85]:
 arr = np.arange(32).reshape((8, 4))

In [86]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [87]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

# Transposing Arrays and Swapping Axes
Transposing is a special form of reshaping that similarly returns a view on the under‐ lying data without copying anything. Arrays have the transpose method and also the special T attribute:

In [88]:
arr = np.arange(15).reshape((3, 5))

In [89]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
arr.T  # row into columns transform

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [91]:
 arr = np.random.randn(6, 3)

In [92]:
arr

array([[-0.94151726, -0.66946672, -1.48858003],
       [ 1.42137654, -0.23722841, -0.44940882],
       [-0.10891616, -2.35978722,  0.6368509 ],
       [-1.80286381, -0.17848785, -0.18282214],
       [-0.44008608, -0.98631194, -1.42269051],
       [-1.12488167, -0.71618274,  1.11903051]])

In [93]:
np.dot(arr.T, arr)  # When doing matrix computations,
#you may do this very often—for example, when computing the inner matrix product using np.dot:

array([[7.62798118, 2.11161483, 0.3903141 ],
       [2.11161483, 7.59064562, 0.23475254],
       [0.3903141 , 0.23475254, 6.13311935]])

In [94]:
arr = np.arange(16).reshape((2, 2, 4))  # 2 rows nested matrix


In [95]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [96]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [97]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [98]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# 4.2 Universal Functions: Fast Element-Wise Array
Functions

In [100]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [102]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [103]:
 x = np.random.randn(8)
    
    

In [104]:
y= np.random.randn(8)
    

In [105]:
x

array([-1.53140883,  1.64306413, -0.99148039,  1.08459937,  1.03107393,
       -2.86497658, -1.08036074,  1.2651372 ])

In [106]:
y

array([-0.17743038,  1.11632787,  1.17235113,  0.64551949, -1.16332763,
       -0.67118544, -1.07696118,  0.42400909])

In [108]:
np.maximum(x, y)

array([-0.17743038,  1.64306413,  1.17235113,  1.08459937,  1.03107393,
       -0.67118544, -1.07696118,  1.2651372 ])

In [110]:
 arr = np.random.randn(7) * 5
arr

array([ 9.44010522,  0.63561221, -0.44709015,  3.58176747,  5.04694061,
       -3.74824579, -1.74941942])

In [111]:
remainder, whole_part = np.modf(arr)

In [112]:
remainder

array([ 0.44010522,  0.63561221, -0.44709015,  0.58176747,  0.04694061,
       -0.74824579, -0.74941942])

In [113]:
whole_part

array([ 9.,  0., -0.,  3.,  5., -3., -1.])

In [114]:
arr

array([ 9.44010522,  0.63561221, -0.44709015,  3.58176747,  5.04694061,
       -3.74824579, -1.74941942])

In [115]:
np.sqrt(arr)

/var/folders/3c/hxpmknwd5cg9lwydrkf402qw0000gp/T/ipykernel_10534/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([3.07247542, 0.79725291,        nan, 1.8925558 , 2.2465397 ,
              nan,        nan])

In [116]:
 np.sqrt(arr, arr)

/var/folders/3c/hxpmknwd5cg9lwydrkf402qw0000gp/T/ipykernel_10534/2830755916.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([3.07247542, 0.79725291,        nan, 1.8925558 , 2.2465397 ,
              nan,        nan])

In [117]:
arr


array([3.07247542, 0.79725291,        nan, 1.8925558 , 2.2465397 ,
              nan,        nan])

# 4.3 Array-Oriented Programming with Arrays

In [118]:
points = np.arange(-5, 5, 0.01)

In [119]:
xs, ys = np.meshgrid(points, points)

In [120]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])