In [4]:
import pandas as pd
import numpy as np
obj=pd.Series([1,2,3,4,5])  # index it will display
obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [18]:
obj.values  # element of that obj

array([1, 2, 3, 4, 5])

In [19]:
obj.index  # range from which it start, stop and step

RangeIndex(start=0, stop=5, step=1)

In [25]:
s1=pd.Series([1,2,3,-4,5], index=['d','a','c','f','h'])  
s1

d    1
a    2
c    3
f   -4
h    5
dtype: int64

In [26]:
s1.index

Index(['d', 'a', 'c', 'f', 'h'], dtype='object')

In [27]:
 s1['a']  # corresponding index value

2

In [28]:
s1[['d','c','h']] # it treats as indices even they are strings

d    1
c    3
h    5
dtype: int64

In [29]:
s1[s1>0]  # prints values greather than zero

d    1
a    2
c    3
h    5
dtype: int64

In [30]:
s1 * 2  # specified operation it perform

d     2
a     4
c     6
f    -8
h    10
dtype: int64

In [31]:
np.exp(s1)  

d      2.718282
a      7.389056
c     20.085537
f      0.018316
h    148.413159
dtype: float64

In [32]:
'a' in s1  # index 'a' exist s1 

True

In [33]:
'v' in s1 # doesn't exist

False

In [37]:
sdata={'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
s2=pd.Series(sdata)  # dict passing in Series it display data in tabular form
s2

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [39]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
s3=pd.Series(sdata,index=states)
s3

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [40]:
pd.isnull(s3)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [41]:
pd.notnull(s3)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [43]:
s2

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [44]:
s3

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [46]:
s2+s3 


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [47]:
s3.name='population'
s3.index.name='state'  # state column nane labeled
s3

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [48]:
s


0    1
1    2
2    3
3    4
4    5
dtype: int64

In [50]:
s.index=['Bob', 'Steve', 'Jeff', 'Ryan','mike']  # Index changed
s

Bob      1
Steve    2
Jeff     3
Ryan     4
mike     5
dtype: int64

# DataFrame
DF rectangular table of data and contains ab ordered collection of columns .DataFrames has both row and column index.It is treated as dict of Series all sharing same indes.Data is stored as one or more two dimensiona block rather than list, dict.

In [54]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [55]:
frame  #DF displays data in tabular form, keys columns label

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [57]:
pd.DataFrame(data,columns=['year','state','pop'])# changing the column order

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [58]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four',
'five', 'six'])

In [59]:
frame2  # new column added with indecies One to Six

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [60]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [62]:
frame2['state'] # displays state columns values

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [63]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [65]:
frame2.loc['three']


year     2002
state    Ohio
pop       3.6
debt     23.5
Name: three, dtype: object

In [66]:
frame2['debt']=23.5
frame2  # all debt values are assigned 23.5

year   state  pop  debt
one    2000    Ohio  1.5  23.5
two    2001    Ohio  1.7  23.5
three  2002    Ohio  3.6  23.5
four   2001  Nevada  2.4  23.5
five   2002  Nevada  2.9  23.5
six    2003  Nevada  3.2  23.5

In [74]:
frame2['debt']=np.arange(6.)  # number of rows put it in asending order

In [71]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [76]:
val=pd.Series([-1.2,-1.6,-1.8],index=['two','four','five'])
frame2['debt']=val# assigning val to debt column for those index
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.6
five   2002  Nevada  2.9  -1.8
six    2003  Nevada  3.2   NaN

In [77]:
frame2['eastern']=frame2.state == 'Ohio'  # for ohio state we are settig eastern True
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.6    False
five   2002  Nevada  2.9  -1.8    False
six    2003  Nevada  3.2   NaN    False

In [78]:
del frame2['eastern']  # delete eastern clomun 

In [79]:
frame2.columns   

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [80]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.6
five   2002  Nevada  2.9  -1.8
six    2003  Nevada  3.2   NaN

In [82]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}


In [85]:
frame3=pd.DataFrame(pop)  #pop dict adding to frame3 dataframe
frame3  

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [86]:
frame3.T  # Intercahnge columns and rows

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [88]:
pd.DataFrame(pop,index=[2001,2002,2003]) # setting index back 


Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [89]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [90]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [91]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.6],
       [2002, 'Nevada', 2.9, -1.8],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

# Index objects


In [92]:
obj=pd.Series(range(3),index=['a','b','c'])
index=obj.index
index
                              

Index(['a', 'b', 'c'], dtype='object')

In [94]:
index[1:] # from 1, index ob are immutable and can't be modidied by user


Index(['b', 'c'], dtype='object')

In [96]:
#index[1]='d' # type error we can;'t modify thr index'

In [97]:
labels=pd.Index(np.arange(3)) # column 0 to 2

In [98]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [99]:
obj2=pd.Series([1.5,-2.4,0],index=labels)
obj2

0    1.5
1   -2.4
2    0.0
dtype: float64

In [100]:
obj2.index is labels


True

In [101]:
frame3


Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [105]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [108]:
'Ohio' in frame3.columns

True

In [110]:
2003 in frame3.index

False

In [111]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [112]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [114]:
 obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) # reassigned index to obj2
obj2
    

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [116]:
 obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [117]:
obj3.reindex(range(6), method='ffill') # 0 to 5

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [119]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame # reshape the frame 3 cross 3

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [121]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [123]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)  #frame reassigning column

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [132]:
frame.loc[['a', 'b', 'c', 'd'], states]  
# row b should gets added up 


KeyError: "['b'] not in index"

In [133]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [134]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [135]:
new_obj=obj.drop('c') # removed c row

In [136]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [137]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [138]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
data.drop(['Colorado', 'Ohio']) # drop index/row if given in list []


one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data

In [142]:
data.drop('two', axis=1) # axis means 

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [143]:
data.drop(['two', 'four'], axis='columns')   

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

#Be careful with the inplace, as it destroys any data that is dropped.
#Many functions, like drop, which modify the size or shape of a Series or DataFrame, can manipulate an object in-place without returning a new object:


In [146]:
obj.drop('b', inplace=True)   # as I already destroyed c now its allowing to use c
obj

a    0.0
d    3.0
e    4.0
dtype: float64

# Indexing, Selection, and Filtering

In [148]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [149]:
obj['b']

1.0

In [150]:
obj[1]

1.0

In [151]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [152]:
 obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [153]:
obj[[1,3]] # display 1,3

b    1.0
d    3.0
dtype: float64

In [154]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [155]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [156]:
obj['b':'c'] = 5

In [157]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [5]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [6]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [7]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [8]:
data[:2]  # 0,1
  

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [9]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [10]:
data<5 # 1st 5 elements

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [13]:
data[data <5] =0  # 1st 5 elements =0
data 

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

# Selection with loc and iloc
For DataFrame label-indexing on the rows, I introduce the special indexing operators loc and iloc. They enable you to select a subset of the rows and columns from a DataFrame with NumPy-like notation using either axis labels (loc) or integers (iloc)

In [16]:
data.loc['Colorado', ['two', 'three']] # that location element usiong name 

two      5
three    6
Name: Colorado, dtype: int64

In [17]:
 data.iloc[2, [3, 0, 1]] # using integers

four    11
one      8
two      9
Name: Utah, dtype: int64

In [18]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [19]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [20]:
data.loc[:'Utah', 'two'] # upto Utah

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [21]:
data.iloc[:, :3][data.three > 5] # not that clear

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [22]:
ser = pd.Series(np.arange(3.))

In [23]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [27]:
 ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [28]:
ser2[-1]

2.0

In [29]:
ser[:1]

0    0.0
dtype: float64

In [30]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [31]:
ser.iloc[:1]

0    0.0
dtype: float64

In [32]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [33]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [34]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [35]:
s2


a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [36]:
s1+s2  # if only have other doesn;t then NAN

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [37]:

 df1= pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [40]:
df2= pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [38]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [41]:
df2


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [42]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [43]:
 df1= pd.DataFrame({'A': [1, 2]})

In [44]:
df2=pd.DataFrame({'B':[3,4]})

In [45]:
df1


b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [46]:
df2

B
0  3
1  4

In [47]:
df1-df2


B   b   c   d
0        NaN NaN NaN NaN
1        NaN NaN NaN NaN
Colorado NaN NaN NaN NaN
Ohio     NaN NaN NaN NaN
Texas    NaN NaN NaN NaN

In [55]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [56]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))



In [60]:
df2.loc[1,'b']=np.nan


In [57]:
df1


a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [61]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [62]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [63]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [64]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [65]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [67]:
arr= np.arange(12.).reshape((3, 4))

In [68]:
arr


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [69]:
arr[0]

array([0., 1., 2., 3.])

In [70]:
arr -arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [71]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [72]:
series=frame.iloc[0]

In [73]:
frame


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [74]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [75]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [77]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [78]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [79]:
series3 = frame['d']

In [80]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [81]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [82]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [83]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [84]:
frame


b         d         e
Utah    0.415802  1.003187 -0.670950
Ohio    0.591801 -0.754636 -0.034849
Texas   0.397584  0.714524  1.232965
Oregon -1.065345  1.196650  3.340854

In [85]:
np.abs(frame)

b         d         e
Utah    0.415802  1.003187  0.670950
Ohio    0.591801  0.754636  0.034849
Texas   0.397584  0.714524  1.232965
Oregon  1.065345  1.196650  3.340854

In [104]:

f=lambda x:x.max() - x.min()

In [105]:
frame.apply(f)

b    1.657146
d    1.951286
e    4.011804
dtype: float64

In [107]:
frame.apply(f,axis='columns')

Utah      1.674137
Ohio      1.346437
Texas     0.835381
Oregon    4.406199
dtype: float64

In [108]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])


In [112]:
frame.apply(f)

b         d         e
min -1.065345 -0.754636 -0.670950
max  0.591801  1.196650  3.340854

In [113]:
format = lambda x: '%.2f' % x

In [114]:
frame.applymap(format)

b      d      e
Utah     0.42   1.00  -0.67
Ohio     0.59  -0.75  -0.03
Texas    0.40   0.71   1.23
Oregon  -1.07   1.20   3.34

In [115]:

frame['e'].map(format)

Utah      -0.67
Ohio      -0.03
Texas      1.23
Oregon     3.34
Name: e, dtype: object

# Sorting and Ranking
Sorting a dataset by some criterion is another important built-in operation. To sort lexicographically by row or column index, use the sort_index method, which returns a new, sorted object:

In [116]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [117]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [118]:
frame=pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
columns=['d', 'a', 'b', 'c'])

In [119]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [122]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [123]:
frame.sort_index(axis=1, ascending=False) # from column 1 decending 

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [124]:
obj = pd.Series([4, 7, -3, 2])

In [125]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [126]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [127]:
obj.sort_values()  # sort basis of values

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [128]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})


In [131]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [133]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [134]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [135]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [136]:
obj.rank() # assign mean to all values 

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [138]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [137]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [140]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
 'c':[-2, 5, 8, -2.5]})

In [141]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [142]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

# Axis Indexes with Duplicate Labels

In [143]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [144]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [145]:
obj.index.is_unique

False

In [146]:
obj['a']

a    0
a    1
dtype: int64

In [147]:
obj['c']

4

In [148]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [149]:
df

0         1         2
a  0.275326  0.368252  1.017043
a  0.358191  1.398693  0.243718
b -1.193677  0.219929 -0.817275
b -0.802930 -1.087272 -1.208501

In [152]:
df.loc['b']

0         1         2
b -1.193677  0.219929 -0.817275
b -0.802930 -1.087272 -1.208501

In [154]:
df= pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])

In [159]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [160]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [161]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [162]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [163]:
df.idxmax()

one    b
two    d
dtype: object

In [164]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [165]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [166]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [167]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [169]:
#conda install pandas-datareader


In [185]:

import pandas_datareader.data as web
all_data= {ticker: web.get_data_yahoo(ticker)
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [186]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
             for ticker, data in all_data.items()}

SyntaxError: unexpected EOF while parsing (1550985810.py, line 4)

In [187]:
returns =price.pct_change()

NameError: name 'price' is not defined